/**
 * 내장 폴백 데이터 (시드)
 * 모든 외부 fetch가 실패해도 빈 화면이 안 뜨도록 최소한의 시드 데이터를 번들에 포함.
 * 2026-05-15 기준 (13R 종료) — 네이버 스포츠 검증값. 스크래퍼가 매일 자동 갱신.
 */

import type {
  StandingsResponse,
  SonResponse,
  Meta,
  ScorersResponse,
  ScheduleResponse,
  FormItem,
  KoreansResponse,
} from './api';

export const FALLBACK_STANDINGS: StandingsResponse = {
  season: 2026,
  updated_at: '2026-05-15T10:30:00.000Z',
  eastern: [
    { rank: 1,  team_id: '18986', team_name: 'Nashville SC',           team_short_name: 'Nashville',   team_abbr: 'NSH',  team_logo: 'https://a.espncdn.com/i/teamlogos/soccer/500/18986.png', played: 13, wins: 8, draws: 3, losses: 2, goals_for: 25, goals_against: 9,  goal_diff: 16, goal_diff_display: '+16', points: 27, recent_form: ['W','W','D','W','W'] as FormItem[] },
    { rank: 2,  team_id: '20232', team_name: 'Inter Miami CF',         team_short_name: 'Miami',       team_abbr: 'MIA',  team_logo: 'https://a.espncdn.com/i/teamlogos/soccer/500/20232.png', played: 13, wins: 8, draws: 2, losses: 3, goals_for: 26, goals_against: 18, goal_diff: 8,  goal_diff_display: '+8',  points: 26, recent_form: ['W','W','W','D','L'] as FormItem[] },
    { rank: 3,  team_id: '189',   team_name: 'New England Revolution', team_short_name: 'New England', team_abbr: 'NE',   team_logo: 'https://a.espncdn.com/i/teamlogos/soccer/500/189.png',   played: 13, wins: 6, draws: 3, losses: 4, goals_for: 22, goals_against: 16, goal_diff: 6,  goal_diff_display: '+6',  points: 21, recent_form: ['W','L','W','D','W'] as FormItem[] },
    { rank: 4,  team_id: '182',   team_name: 'Chicago Fire FC',        team_short_name: 'Chicago',     team_abbr: 'CHI',  team_logo: 'https://a.espncdn.com/i/teamlogos/soccer/500/182.png',   played: 13, wins: 5, draws: 5, losses: 3, goals_for: 18, goals_against: 13, goal_diff: 5,  goal_diff_display: '+5',  points: 20, recent_form: ['D','W','D','W','L'] as FormItem[] },
    { rank: 5,  team_id: '21300', team_name: 'Charlotte FC',           team_short_name: 'Charlotte',   team_abbr: 'CLT',  team_logo: 'https://a.espncdn.com/i/teamlogos/soccer/500/21300.png', played: 13, wins: 5, draws: 4, losses: 4, goals_for: 21, goals_against: 19, goal_diff: 2,  goal_diff_display: '+2',  points: 19, recent_form: ['L','W','W','D','L'] as FormItem[] },
    { rank: 6,  team_id: '7318',  team_name: 'Toronto FC',             team_short_name: 'Toronto',     team_abbr: 'TOR',  team_logo: 'https://a.espncdn.com/i/teamlogos/soccer/500/7318.png',  played: 13, wins: 4, draws: 6, losses: 3, goals_for: 21, goals_against: 22, goal_diff: -1, goal_diff_display: '-1',  points: 18, recent_form: ['D','D','W','W','D'] as FormItem[] },
    { rank: 7,  team_id: '17606', team_name: 'New York City FC',       team_short_name: 'NYCFC',       team_abbr: 'NYC',  team_logo: 'https://a.espncdn.com/i/teamlogos/soccer/500/17606.png', played: 13, wins: 4, draws: 5, losses: 4, goals_for: 26, goals_against: 20, goal_diff: 6,  goal_diff_display: '+6',  points: 17, recent_form: ['W','L','D','W','D'] as FormItem[] },
    { rank: 8,  team_id: '190',   team_name: 'Red Bull New York',      team_short_name: 'Red Bull NY', team_abbr: 'RBNY', team_logo: 'https://a.espncdn.com/i/teamlogos/soccer/500/190.png',   played: 13, wins: 4, draws: 5, losses: 4, goals_for: 22, goals_against: 28, goal_diff: -6, goal_diff_display: '-6',  points: 17, recent_form: ['L','D','W','L','W'] as FormItem[] },
    { rank: 9,  team_id: '183',   team_name: 'Columbus Crew',          team_short_name: 'Columbus',    team_abbr: 'CLB',  team_logo: 'https://a.espncdn.com/i/teamlogos/soccer/500/183.png',   played: 13, wins: 3, draws: 5, losses: 5, goals_for: 17, goals_against: 18, goal_diff: -1, goal_diff_display: '-1',  points: 14, recent_form: ['L','L','D','D','W'] as FormItem[] },
    { rank: 10, team_id: '193',   team_name: 'D.C. United',            team_short_name: 'D.C. United', team_abbr: 'DC',   team_logo: 'https://a.espncdn.com/i/teamlogos/soccer/500/193.png',   played: 13, wins: 3, draws: 5, losses: 5, goals_for: 12, goals_against: 17, goal_diff: -5, goal_diff_display: '-5',  points: 14, recent_form: ['D','L','D','L','W'] as FormItem[] },
    { rank: 11, team_id: '18267', team_name: 'FC Cincinnati',          team_short_name: 'Cincinnati',  team_abbr: 'CIN',  team_logo: 'https://a.espncdn.com/i/teamlogos/soccer/500/18267.png', played: 13, wins: 3, draws: 5, losses: 5, goals_for: 23, goals_against: 29, goal_diff: -6, goal_diff_display: '-6',  points: 14, recent_form: ['L','W','D','L','D'] as FormItem[] },
    { rank: 12, team_id: '12011', team_name: 'Orlando City SC',        team_short_name: 'Orlando',     team_abbr: 'ORL',  team_logo: 'https://a.espncdn.com/i/teamlogos/soccer/500/12011.png', played: 13, wins: 3, draws: 4, losses: 6, goals_for: 16, goals_against: 22, goal_diff: -6, goal_diff_display: '-6',  points: 13, recent_form: ['L','L','W','L','D'] as FormItem[] },
    { rank: 13, team_id: '9720',  team_name: 'CF Montréal',            team_short_name: 'Montréal',    team_abbr: 'MTL',  team_logo: 'https://a.espncdn.com/i/teamlogos/soccer/500/9720.png',  played: 13, wins: 3, draws: 3, losses: 7, goals_for: 13, goals_against: 22, goal_diff: -9, goal_diff_display: '-9',  points: 12, recent_form: ['L','L','D','W','L'] as FormItem[] },
    { rank: 14, team_id: '10739', team_name: 'Philadelphia Union',     team_short_name: 'Philadelphia',team_abbr: 'PHI',  team_logo: 'https://a.espncdn.com/i/teamlogos/soccer/500/10739.png', played: 13, wins: 2, draws: 5, losses: 6, goals_for: 13, goals_against: 19, goal_diff: -6, goal_diff_display: '-6',  points: 11, recent_form: ['D','L','D','L','L'] as FormItem[] },
    { rank: 15, team_id: '18418', team_name: 'Atlanta United FC',      team_short_name: 'Atlanta',     team_abbr: 'ATL',  team_logo: 'https://a.espncdn.com/i/teamlogos/soccer/500/18418.png', played: 13, wins: 2, draws: 4, losses: 7, goals_for: 14, goals_against: 24, goal_diff:-10, goal_diff_display: '-10', points: 10, recent_form: ['L','D','L','L','W'] as FormItem[] },
  ],
  western: [
    { rank: 1,  team_id: '9727',  team_name: 'Vancouver Whitecaps',    team_short_name: 'Vancouver',   team_abbr: 'VAN',  team_logo: 'https://a.espncdn.com/i/teamlogos/soccer/500/9727.png',  played: 13, wins: 9, draws: 2, losses: 2, goals_for: 28, goals_against: 11, goal_diff: 17, goal_diff_display: '+17', points: 29, recent_form: ['W','W','W','W','D'] as FormItem[] },
    { rank: 2,  team_id: '22529', team_name: 'San Diego FC',           team_short_name: 'San Diego',   team_abbr: 'SD',   team_logo: 'https://a.espncdn.com/i/teamlogos/soccer/500/22529.png', played: 13, wins: 8, draws: 2, losses: 3, goals_for: 22, goals_against: 13, goal_diff: 9,  goal_diff_display: '+9',  points: 26, recent_form: ['W','D','W','W','L'] as FormItem[] },
    { rank: 3,  team_id: '191',   team_name: 'San Jose Earthquakes',   team_short_name: 'San Jose',    team_abbr: 'SJ',   team_logo: 'https://a.espncdn.com/i/teamlogos/soccer/500/191.png',   played: 13, wins: 7, draws: 4, losses: 2, goals_for: 21, goals_against: 16, goal_diff: 5,  goal_diff_display: '+5',  points: 25, recent_form: ['W','W','D','W','D'] as FormItem[] },
    { rank: 4,  team_id: '17362', team_name: 'Minnesota United FC',    team_short_name: 'Minnesota',   team_abbr: 'MIN',  team_logo: 'https://a.espncdn.com/i/teamlogos/soccer/500/17362.png', played: 13, wins: 6, draws: 5, losses: 2, goals_for: 19, goals_against: 11, goal_diff: 8,  goal_diff_display: '+8',  points: 23, recent_form: ['D','W','W','D','W'] as FormItem[] },
    { rank: 5,  team_id: '18966', team_name: 'Los Angeles FC',         team_short_name: 'LAFC',        team_abbr: 'LAFC', team_logo: 'https://a.espncdn.com/i/teamlogos/soccer/500/18966.png', played: 13, wins: 6, draws: 3, losses: 4, goals_for: 20, goals_against: 16, goal_diff: 4,  goal_diff_display: '+4',  points: 21, recent_form: ['W','L','W','W','D'] as FormItem[] },
    { rank: 6,  team_id: '9726',  team_name: 'Seattle Sounders FC',    team_short_name: 'Seattle',     team_abbr: 'SEA',  team_logo: 'https://a.espncdn.com/i/teamlogos/soccer/500/9726.png',  played: 13, wins: 5, draws: 5, losses: 3, goals_for: 19, goals_against: 14, goal_diff: 5,  goal_diff_display: '+5',  points: 20, recent_form: ['W','D','D','W','D'] as FormItem[] },
    { rank: 7,  team_id: '4771',  team_name: 'Real Salt Lake',         team_short_name: 'Salt Lake',   team_abbr: 'RSL',  team_logo: 'https://a.espncdn.com/i/teamlogos/soccer/500/4771.png',  played: 13, wins: 5, draws: 4, losses: 4, goals_for: 18, goals_against: 16, goal_diff: 2,  goal_diff_display: '+2',  points: 19, recent_form: ['W','W','L','D','D'] as FormItem[] },
    { rank: 8,  team_id: '184',   team_name: 'Colorado Rapids',        team_short_name: 'Colorado',    team_abbr: 'COL',  team_logo: 'https://a.espncdn.com/i/teamlogos/soccer/500/184.png',   played: 13, wins: 5, draws: 3, losses: 5, goals_for: 19, goals_against: 19, goal_diff: 0,  goal_diff_display: '0',   points: 18, recent_form: ['L','W','W','L','D'] as FormItem[] },
    { rank: 9,  team_id: '185',   team_name: 'FC Dallas',              team_short_name: 'Dallas',      team_abbr: 'DAL',  team_logo: 'https://a.espncdn.com/i/teamlogos/soccer/500/185.png',   played: 13, wins: 4, draws: 5, losses: 4, goals_for: 17, goals_against: 18, goal_diff: -1, goal_diff_display: '-1',  points: 17, recent_form: ['D','W','D','L','W'] as FormItem[] },
    { rank: 10, team_id: '6077',  team_name: 'Houston Dynamo FC',      team_short_name: 'Houston',     team_abbr: 'HOU',  team_logo: 'https://a.espncdn.com/i/teamlogos/soccer/500/6077.png',  played: 13, wins: 4, draws: 4, losses: 5, goals_for: 14, goals_against: 17, goal_diff: -3, goal_diff_display: '-3',  points: 16, recent_form: ['L','D','W','D','L'] as FormItem[] },
    { rank: 11, team_id: '187',   team_name: 'LA Galaxy',              team_short_name: 'LA Galaxy',   team_abbr: 'LA',   team_logo: 'https://a.espncdn.com/i/teamlogos/soccer/500/187.png',   played: 13, wins: 3, draws: 5, losses: 5, goals_for: 16, goals_against: 22, goal_diff: -6, goal_diff_display: '-6',  points: 14, recent_form: ['L','L','D','W','D'] as FormItem[] },
    { rank: 12, team_id: '9723',  team_name: 'Portland Timbers',       team_short_name: 'Portland',    team_abbr: 'POR',  team_logo: 'https://a.espncdn.com/i/teamlogos/soccer/500/9723.png',  played: 13, wins: 3, draws: 4, losses: 6, goals_for: 17, goals_against: 22, goal_diff: -5, goal_diff_display: '-5',  points: 13, recent_form: ['L','W','L','L','D'] as FormItem[] },
    { rank: 13, team_id: '20906', team_name: 'Austin FC',              team_short_name: 'Austin',      team_abbr: 'ATX',  team_logo: 'https://a.espncdn.com/i/teamlogos/soccer/500/20906.png', played: 13, wins: 3, draws: 4, losses: 6, goals_for: 12, goals_against: 19, goal_diff: -7, goal_diff_display: '-7',  points: 13, recent_form: ['L','D','L','L','W'] as FormItem[] },
    { rank: 14, team_id: '21812', team_name: 'St. Louis CITY SC',      team_short_name: 'St. Louis',   team_abbr: 'STL',  team_logo: 'https://a.espncdn.com/i/teamlogos/soccer/500/21812.png', played: 13, wins: 2, draws: 6, losses: 5, goals_for: 14, goals_against: 20, goal_diff: -6, goal_diff_display: '-6',  points: 12, recent_form: ['D','L','D','D','D'] as FormItem[] },
    { rank: 15, team_id: '186',   team_name: 'Sporting Kansas City',   team_short_name: 'Kansas City', team_abbr: 'SKC',  team_logo: 'https://a.espncdn.com/i/teamlogos/soccer/500/186.png',   played: 13, wins: 2, draws: 4, losses: 7, goals_for: 13, goals_against: 23, goal_diff:-10, goal_diff_display: '-10', points: 10, recent_form: ['L','L','D','L','W'] as FormItem[] },
  ],
};

// LAFC 손흥민 (2026-05-15 기준, 13경기 0골 7어시)
export const FALLBACK_SON: SonResponse = {
  season: 2026,
  updated_at: '2026-05-15T10:30:00.000Z',
  lafc: {
    team_id: '18966',
    team_name: 'Los Angeles FC',
    team_short_name: 'LAFC',
    team_abbr: 'LAFC',
    team_logo: 'https://a.espncdn.com/i/teamlogos/soccer/500/18966.png',
    venue: 'BMO Stadium',
    color: '#000000',
    rank: 5,
    points: 21,
    played: 13,
    wins: 6,
    draws: 3,
    losses: 4,
    goals_for: 20,
    goals_against: 16,
    goal_diff: 4,
    goal_diff_display: '+4',
  },
  son: {
    player_name: 'Heung-Min Son',
    player_name_ko: '손흥민',
    nationality: 'KR',
    nationality_ko: '대한민국',
    team_name: 'Los Angeles FC',
    team_short_name: 'LAFC',
    position: 'F',
    position_ko: '공격수',
    jersey: '7',
    age: 33,
    photo: 'https://a.espncdn.com/i/headshots/soccer/players/full/149945.png',
    transfer_note: '2025년 여름 토트넘에서 LAFC로 이적. MLS 무대 도전 중!',
    transfer_note_en: 'Joined LAFC from Tottenham in summer 2025.',
    season: 2026,
    appearances: 11,
    goals: 0,
    assists: 7,
    shots: 31,
    shots_on_target: 12,
    minutes: 950,
    yellow_cards: 1,
    red_cards: 0,
    goals_per_match: 0.0,
    league_goal_rank: undefined,
    league_assist_rank: 1,
  },
  last_match: {
    match_id: 'lafc_2026_r13',
    date: '2026-05-14T02:30:00.000Z',
    date_kst: '2026-05-14T11:30:00+09:00',
    kst_display: '2026.05.14 (수) 11:30',
    competition: 'MLS',
    round: 'Regular Season Round 13',
    home: true,
    opponent_id: '21812',
    opponent_name: 'St. Louis CITY SC',
    opponent_short: 'St. Louis',
    opponent_logo: 'https://a.espncdn.com/i/teamlogos/soccer/500/21812.png',
    home_score: 0,
    away_score: 0,
    result: 'D' as FormItem,
    venue: 'BMO Stadium',
    son_played: true,
    son_minutes: 90,
    son_goals: 0,
    son_assists: 0,
    son_shots: 3,
    son_rating: 7.0,
    son_man_of_the_match: false,
    summary: '풀타임 출장하며 3번의 슈팅 시도. 골은 없었지만 위협적인 공격 전개에 기여.',
  },
  next_match: {
    match_id: 'lafc_2026_r14',
    date: '2026-05-18T02:30:00.000Z',
    date_kst: '2026-05-18T11:30:00+09:00',
    kst_display: '2026.05.18 (일) 11:30',
    competition: 'MLS',
    round: 'Regular Season Round 14',
    home: false,
    opponent_id: '187',
    opponent_name: 'LA Galaxy',
    opponent_short: 'LA Galaxy',
    opponent_logo: 'https://a.espncdn.com/i/teamlogos/soccer/500/187.png',
    venue: 'Dignity Health Sports Park',
    days_until: 3,
    preview: '🔥 엘 트라피코 더비! LA 라이벌 LA갤럭시 원정. 손흥민의 첫 더비 활약 기대.',
  },
};

// 득점왕/어시스트왕 (2026-05-15, 네이버 스포츠 검증값)
export const FALLBACK_SCORERS: ScorersResponse = {
  season: 2026,
  updated_at: '2026-05-15T10:30:00.000Z',
  scorers: [
    { rank: 1, player_id: 'cuypers',  player_name: 'Hugo Cuypers',     player_name_ko: '위고 카이퍼스',   nationality: 'BE', team_id: '182',   team_name: 'Chicago Fire FC',     team_short: 'Chicago',   team_logo: 'https://a.espncdn.com/i/teamlogos/soccer/500/182.png',   goals: 12, played: 13, penalties: 2 },
    { rank: 2, player_id: 'messi',    player_name: 'Lionel Messi',     player_name_ko: '리오넬 메시',     nationality: 'AR', team_id: '20232', team_name: 'Inter Miami CF',      team_short: 'Miami',     team_logo: 'https://a.espncdn.com/i/teamlogos/soccer/500/20232.png', goals: 11, played: 12, penalties: 1 },
    { rank: 2, player_id: 'musa',     player_name: 'Sam Surridge',     player_name_ko: '샘 서리지',       nationality: 'EN', team_id: '18986', team_name: 'Nashville SC',        team_short: 'Nashville', team_logo: 'https://a.espncdn.com/i/teamlogos/soccer/500/18986.png', goals: 11, played: 13, penalties: 1 },
    { rank: 4, player_id: 'bouanga',  player_name: 'Denis Bouanga',    player_name_ko: '드니 부앙가',     nationality: 'GA', team_id: '18966', team_name: 'Los Angeles FC',      team_short: 'LAFC',      team_logo: 'https://a.espncdn.com/i/teamlogos/soccer/500/18966.png', goals: 9,  played: 13, penalties: 1 },
    { rank: 5, player_id: 'lletget',  player_name: 'Anders Dreyer',    player_name_ko: '안데르스 드레이어',nationality: 'DK', team_id: '22529', team_name: 'San Diego FC',        team_short: 'San Diego', team_logo: 'https://a.espncdn.com/i/teamlogos/soccer/500/22529.png', goals: 9,  played: 13, penalties: 0 },
    { rank: 6, player_id: 'martinez', player_name: 'Josef Martínez',   player_name_ko: '호세프 마르티네스',nationality: 'VE', team_id: '17606', team_name: 'New York City FC',    team_short: 'NYCFC',     team_logo: 'https://a.espncdn.com/i/teamlogos/soccer/500/17606.png', goals: 8,  played: 12, penalties: 1 },
    { rank: 7, player_id: 'suarez',   player_name: 'Luis Suárez',      player_name_ko: '루이스 수아레스', nationality: 'UY', team_id: '20232', team_name: 'Inter Miami CF',      team_short: 'Miami',     team_logo: 'https://a.espncdn.com/i/teamlogos/soccer/500/20232.png', goals: 8,  played: 11, penalties: 1 },
    { rank: 8, player_id: 'almada',   player_name: 'Thiago Almada',    player_name_ko: '티아고 알마다',   nationality: 'AR', team_id: '20232', team_name: 'Inter Miami CF',      team_short: 'Miami',     team_logo: 'https://a.espncdn.com/i/teamlogos/soccer/500/20232.png', goals: 7,  played: 13, penalties: 0 },
    { rank: 9, player_id: 'morris',   player_name: 'Jordan Morris',    player_name_ko: '조던 모리스',     nationality: 'US', team_id: '9726',  team_name: 'Seattle Sounders FC', team_short: 'Seattle',   team_logo: 'https://a.espncdn.com/i/teamlogos/soccer/500/9726.png',  goals: 7,  played: 13, penalties: 0 },
    { rank: 10,player_id: 'gabriel',  player_name: 'Brian Gutiérrez',  player_name_ko: '브라이언 구티에레스',nationality: 'US',team_id: '182',  team_name: 'Chicago Fire FC',     team_short: 'Chicago',   team_logo: 'https://a.espncdn.com/i/teamlogos/soccer/500/182.png',   goals: 7,  played: 13, penalties: 0 },
  ],
  assisters: [
    { rank: 1, player_id: '178194',   player_name: 'Heung-Min Son',    player_name_ko: '손흥민',          nationality: 'KR', team_id: '18966', team_name: 'Los Angeles FC',      team_short: 'LAFC',      team_logo: 'https://a.espncdn.com/i/teamlogos/soccer/500/18966.png', assists: 7, played: 11 },
    { rank: 2, player_id: 'langoni',  player_name: 'Julian Fernández', player_name_ko: '훌리안 페르난데스',nationality: 'AR', team_id: '190',   team_name: 'Red Bull New York',   team_short: 'Red Bull NY',team_logo: 'https://a.espncdn.com/i/teamlogos/soccer/500/190.png',  assists: 6, played: 13 },
    { rank: 2, player_id: 'morales',  player_name: 'Diego Luna',       player_name_ko: '디에고 루나',     nationality: 'US', team_id: '4771',  team_name: 'Real Salt Lake',      team_short: 'Salt Lake', team_logo: 'https://a.espncdn.com/i/teamlogos/soccer/500/4771.png',  assists: 6, played: 13 },
    { rank: 4, player_id: 'dreyer',   player_name: 'Anders Dreyer',    player_name_ko: '안데르스 드레이어',nationality: 'DK', team_id: '22529', team_name: 'San Diego FC',        team_short: 'San Diego', team_logo: 'https://a.espncdn.com/i/teamlogos/soccer/500/22529.png', assists: 5, played: 13 },
    { rank: 5, player_id: 'almada',   player_name: 'Thiago Almada',    player_name_ko: '티아고 알마다',   nationality: 'AR', team_id: '20232', team_name: 'Inter Miami CF',      team_short: 'Miami',     team_logo: 'https://a.espncdn.com/i/teamlogos/soccer/500/20232.png', assists: 5, played: 13 },
    { rank: 6, player_id: 'messi',    player_name: 'Lionel Messi',     player_name_ko: '리오넬 메시',     nationality: 'AR', team_id: '20232', team_name: 'Inter Miami CF',      team_short: 'Miami',     team_logo: 'https://a.espncdn.com/i/teamlogos/soccer/500/20232.png', assists: 5, played: 12 },
    { rank: 7, player_id: 'gutman',   player_name: 'Sam Gutman',       player_name_ko: '샘 굿먼',         nationality: 'US', team_id: '189',   team_name: 'New England Revolution',team_short:'New England',team_logo: 'https://a.espncdn.com/i/teamlogos/soccer/500/189.png',   assists: 5, played: 13 },
    { rank: 8, player_id: 'bouanga',  player_name: 'Denis Bouanga',    player_name_ko: '드니 부앙가',     nationality: 'GA', team_id: '18966', team_name: 'Los Angeles FC',      team_short: 'LAFC',      team_logo: 'https://a.espncdn.com/i/teamlogos/soccer/500/18966.png', assists: 4, played: 13 },
    { rank: 9, player_id: 'rusnak',   player_name: 'Albert Rusnák',    player_name_ko: '알베르트 루스냐크',nationality: 'SK', team_id: '9726',  team_name: 'Seattle Sounders FC', team_short: 'Seattle',   team_logo: 'https://a.espncdn.com/i/teamlogos/soccer/500/9726.png',  assists: 4, played: 13 },
    { rank: 10,player_id: 'driussi',  player_name: 'Sebastián Driussi',player_name_ko: '세바스티안 드리우시',nationality: 'AR', team_id: '20906',team_name: 'Austin FC',          team_short: 'Austin',    team_logo: 'https://a.espncdn.com/i/teamlogos/soccer/500/20906.png', assists: 4, played: 13 },
  ],
};

// 코리안 리거 (LAFC 손흥민 + Inter Miami 정상빈 등)
export const FALLBACK_KOREANS: KoreansResponse = {
  season: 2026,
  updated_at: '2026-05-15T10:30:00.000Z',
  players: [
    {
      player_id: '178194',
      player_name: 'Heung-Min Son',
      player_name_ko: '손흥민',
      position: 'F',
      jersey: '7',
      age: 33,
      photo: 'https://a.espncdn.com/i/headshots/soccer/players/full/149945.png',
      team_id: '18966',
      team_name: 'Los Angeles FC',
      team_short: 'LAFC',
      team_logo: 'https://a.espncdn.com/i/teamlogos/soccer/500/18966.png',
      appearances: 11,
      goals: 0,
      assists: 7,
      shots: 31,
      shots_on_target: 12,
      minutes: 950,
    },
    {
      player_id: 'jeong_sangbin',
      player_name: 'Sang-Bin Jeong',
      player_name_ko: '정상빈',
      position: 'F',
      jersey: '24',
      age: 23,
      photo: '',
      team_id: '20232',
      team_name: 'Inter Miami CF',
      team_short: 'Miami',
      team_logo: 'https://a.espncdn.com/i/teamlogos/soccer/500/20232.png',
      appearances: 7,
      goals: 1,
      assists: 0,
      shots: 8,
      shots_on_target: 3,
      minutes: 380,
    },
  ],
};

// 메타
export const FALLBACK_META: Meta = {
  season: 2026,
  league_name: 'Major League Soccer',
  league_abbr: 'MLS',
  league_name_ko: 'MLS',
  updated_at: '2026-05-15T10:30:00.000Z',
  source: 'ESPN MLS API',
  version: '4.0.0',
};

// 팀별 일정 (LAFC, Miami, Nashville, Vancouver, San Jose 핵심팀 — 다음 경기 opponent_stats 포함)
export const FALLBACK_SCHEDULE: ScheduleResponse = {
  season: 2026,
  updated_at: '2026-05-15T10:30:00.000Z',
  schedule: {
    // ── LAFC ──
    '18966': {
      last: {
        match_id: 'lafc_2026_r13',
        date: '2026-05-14T02:30:00.000Z',
        date_kst: '2026-05-14T11:30:00+09:00',
        kst_display: '2026.05.14 (수) 11:30',
        home: true,
        opponent_id: '21812',
        opponent_name: 'St. Louis CITY SC',
        opponent_short: 'St. Louis',
        opponent_logo: 'https://a.espncdn.com/i/teamlogos/soccer/500/21812.png',
        home_score: 0,
        away_score: 0,
        result: 'D' as FormItem,
        venue: 'BMO Stadium',
        round: 'Regular Season Round 13',
      },
      next: {
        match_id: 'lafc_2026_r14',
        date: '2026-05-18T02:30:00.000Z',
        date_kst: '2026-05-18T11:30:00+09:00',
        kst_display: '2026.05.18 (일) 11:30',
        home: false,
        opponent_id: '187',
        opponent_name: 'LA Galaxy',
        opponent_short: 'LA Galaxy',
        opponent_logo: 'https://a.espncdn.com/i/teamlogos/soccer/500/187.png',
        venue: 'Dignity Health Sports Park',
        days_until: 3,
        round: 'Regular Season Round 14',
        opponent_stats: {
          rank: 11, points: 14, played: 13, wins: 3, draws: 5, losses: 5,
          goals_for: 16, goals_against: 22,
          recent_form: ['L','L','D','W','D'] as FormItem[],
        },
      },
    },
    // ── Inter Miami ──
    '20232': {
      last: {
        match_id: 'mia_2026_r13',
        date: '2026-05-13T23:30:00.000Z',
        date_kst: '2026-05-14T08:30:00+09:00',
        kst_display: '2026.05.14 (수) 08:30',
        home: true,
        opponent_id: '193',
        opponent_name: 'D.C. United',
        opponent_short: 'D.C.',
        opponent_logo: 'https://a.espncdn.com/i/teamlogos/soccer/500/193.png',
        home_score: 3,
        away_score: 1,
        result: 'W' as FormItem,
        venue: 'Chase Stadium',
        round: 'Regular Season Round 13',
      },
      next: {
        match_id: 'mia_2026_r14',
        date: '2026-05-17T23:30:00.000Z',
        date_kst: '2026-05-18T08:30:00+09:00',
        kst_display: '2026.05.18 (일) 08:30',
        home: false,
        opponent_id: '17606',
        opponent_name: 'New York City FC',
        opponent_short: 'NYCFC',
        opponent_logo: 'https://a.espncdn.com/i/teamlogos/soccer/500/17606.png',
        venue: 'Yankee Stadium',
        days_until: 3,
        round: 'Regular Season Round 14',
        opponent_stats: {
          rank: 7, points: 17, played: 13, wins: 4, draws: 5, losses: 4,
          goals_for: 26, goals_against: 20,
          recent_form: ['W','L','D','W','D'] as FormItem[],
        },
      },
    },
    // ── Nashville ──
    '18986': {
      last: {
        match_id: 'nsh_2026_r13',
        date: '2026-05-13T23:30:00.000Z',
        date_kst: '2026-05-14T08:30:00+09:00',
        kst_display: '2026.05.14 (수) 08:30',
        home: false,
        opponent_id: '21300',
        opponent_name: 'Charlotte FC',
        opponent_short: 'Charlotte',
        opponent_logo: 'https://a.espncdn.com/i/teamlogos/soccer/500/21300.png',
        home_score: 2,
        away_score: 1,
        result: 'W' as FormItem,
        venue: 'Bank of America Stadium',
        round: 'Regular Season Round 13',
      },
      next: {
        match_id: 'nsh_2026_r14',
        date: '2026-05-18T01:30:00.000Z',
        date_kst: '2026-05-18T10:30:00+09:00',
        kst_display: '2026.05.18 (일) 10:30',
        home: true,
        opponent_id: '182',
        opponent_name: 'Chicago Fire FC',
        opponent_short: 'Chicago',
        opponent_logo: 'https://a.espncdn.com/i/teamlogos/soccer/500/182.png',
        venue: 'Geodis Park',
        days_until: 3,
        round: 'Regular Season Round 14',
        opponent_stats: {
          rank: 4, points: 20, played: 13, wins: 5, draws: 5, losses: 3,
          goals_for: 18, goals_against: 13,
          recent_form: ['D','W','D','W','L'] as FormItem[],
        },
      },
    },
    // ── Vancouver Whitecaps ──
    '9727': {
      last: {
        match_id: 'van_2026_r13',
        date: '2026-05-14T02:30:00.000Z',
        date_kst: '2026-05-14T11:30:00+09:00',
        kst_display: '2026.05.14 (수) 11:30',
        home: true,
        opponent_id: '186',
        opponent_name: 'Sporting Kansas City',
        opponent_short: 'Kansas City',
        opponent_logo: 'https://a.espncdn.com/i/teamlogos/soccer/500/186.png',
        home_score: 2,
        away_score: 2,
        result: 'D' as FormItem,
        venue: 'BC Place',
        round: 'Regular Season Round 13',
      },
      next: {
        match_id: 'van_2026_r14',
        date: '2026-05-18T02:30:00.000Z',
        date_kst: '2026-05-18T11:30:00+09:00',
        kst_display: '2026.05.18 (일) 11:30',
        home: false,
        opponent_id: '9723',
        opponent_name: 'Portland Timbers',
        opponent_short: 'Portland',
        opponent_logo: 'https://a.espncdn.com/i/teamlogos/soccer/500/9723.png',
        venue: 'Providence Park',
        days_until: 3,
        round: 'Regular Season Round 14',
        opponent_stats: {
          rank: 12, points: 13, played: 13, wins: 3, draws: 4, losses: 6,
          goals_for: 17, goals_against: 22,
          recent_form: ['L','W','L','L','D'] as FormItem[],
        },
      },
    },
    // ── San Jose Earthquakes ──
    '191': {
      last: {
        match_id: 'sj_2026_r13',
        date: '2026-05-14T02:30:00.000Z',
        date_kst: '2026-05-14T11:30:00+09:00',
        kst_display: '2026.05.14 (수) 11:30',
        home: false,
        opponent_id: '22529',
        opponent_name: 'San Diego FC',
        opponent_short: 'San Diego',
        opponent_logo: 'https://a.espncdn.com/i/teamlogos/soccer/500/22529.png',
        home_score: 1,
        away_score: 1,
        result: 'D' as FormItem,
        venue: 'Snapdragon Stadium',
        round: 'Regular Season Round 13',
      },
      next: {
        match_id: 'sj_2026_r14',
        date: '2026-05-18T02:30:00.000Z',
        date_kst: '2026-05-18T11:30:00+09:00',
        kst_display: '2026.05.18 (일) 11:30',
        home: true,
        opponent_id: '17362',
        opponent_name: 'Minnesota United FC',
        opponent_short: 'Minnesota',
        opponent_logo: 'https://a.espncdn.com/i/teamlogos/soccer/500/17362.png',
        venue: 'PayPal Park',
        days_until: 3,
        round: 'Regular Season Round 14',
        opponent_stats: {
          rank: 4, points: 23, played: 13, wins: 6, draws: 5, losses: 2,
          goals_for: 19, goals_against: 11,
          recent_form: ['D','W','W','D','W'] as FormItem[],
        },
      },
    },
  },
};
